source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SMSwipeableTabView_Example', :exclusive => true do
  pod "SMSwipeableTabView", :path => "../"
end

target 'SMSwipeableTabView_Tests', :exclusive => true do
  pod "SMSwipeableTabView", :path => "../"

  
end
